### ISSUE TITLE
GPX dateTime error: "is not one of the supported formats"

### ISSUE THREAD

**Issue by milovanderlinden** [anitagraser/TimeManager#30] opened 2012-10-22 12:01 UTC
I am trying to add a GPX file directly to the TimeManager by using the following steps:

1. Ctrl + Shift + V (add vector layer)
2. Select GPS eXchange Format [GPX] [OGR]
3. Open the file, select the trackpoints to be displayed as layer

Now when investigating the properties of my layer, I can see that the "time" column is of type dateTime.

4. Click "Settings" in the TimeManager widget
5. Add layer, select "time" column
6. I get the error:

An error occured while trying to add layer track_points to TimeManager.
track_points: The attribute specified for use as start time contains invalid data:

is not one of the supported formats:
['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%Y/%m/%d %H:%M:%S']

I read through the source and found out that in the blank section in the error message above, it should print the string value from the column. Since it doesn't, I assume that the dateTime column cannot be read.

I am digging throught the code to see if I can come up with a fix myself. If I do, I will send you a pull request.

Kind regards,

Milo

**Comment by carolinux** [comment] 2015-01-27 11:45
Closing this as a duplicate of #33

**Closed by carolinux** 2015-01-27 11:45 UTC
Labels: bug
