### ISSUE TITLE
Add support for categorized renderer when interpolating features

### ISSUE THREAD

**Issue by 1kastner** [anitagraser/TimeManager#224] opened 2017-04-02 15:06 UTC
When I tried to create an animation today I happened to get this error message in an info popup:

`An error occured while trying to add layer january_2016 to TimeManager. Cause: 'Traceback:Traceback (most recent call last):\n  File "C:/Users/MYUSERNAME/.qgis2/python/plugins\\timemanager\\timevectorinterpolatedlayer.py", line 53, in __init__\n    qgs.setLayerColor(self.memLayer, qgs.getLayerColor(self.layer))\n  File "C:/Users/MYUSERNAME/.qgis2/python/plugins\\timemanager\\qgis_utils.py", line 116, in getLayerColor\n    symbol = renderer.symbol()\nAttributeError: \'QgsCategorizedSymbolRendererV2\' object has no attribute \'symbol\'\n`

This happened after I imported my csv, created labels etc. and then I wanted to add it to TimeManager in order to create a video from it. To my knowledge I did nothing odd or I am not aware of having any kind of edge-case.

**Comment by anitagraser** [comment] 2017-04-02 15:53
The only case that causes errors related to renderers that I am aware of is when interpolation is used. Can you describe your settings?

**Comment by 1kastner** [comment] 2017-04-02 16:38
In fact I use interpolation, here are some sample lines from the csv file:

`location_id,lat,lon,time,tempm,dewptm,wspdm,wgustm,wdird,pressurem,hum
IHG1677,54.588959,13.010760,2016-01-12 01:07:00,2.9,2.1,-1608.8,-1607.4,-9999,983.6,94
IHG1677,54.588959,13.010760,2016-01-12 04:50:00,2.9,2.4,-1608.8,-1607.4,-9999,984.3,97
INERS755,54.651192,12.997177,2016-01-21 03:52:00,-2.2,-3.9,-1608.8,-1607.4,-9999,1023.6,88
INERS755,54.651192,12.997177,2016-01-21 04:22:00,-2.2,-3.9,-1608.8,-1607.4,-9999,1024.3,88`

Actually the locations are fixed but in order to use TimeManager I modified the data so that each data point has its coordinates as well. Starting with "time" the other values are the measurements.
The data at each location is refreshed in different time intervals. Approx. each 10 minutes there is a new value but also a lot of missing data exists. As in any minute an update can come, the animation should be minute-based. To avoid flickering interpolation should be used. 

As a contextual information: In further steps of course more sophisticated interpolation functions should be used as interpolation over several days do not make much sense but we always need to start somewhere.

**Comment by anitagraser** [comment] 2017-04-02 17:54
Currently, TimeManager's interpolation feature can only be used with a single symbol renderer. Categorized renderers are not supported

**Comment by 1kastner** [comment] 2017-04-02 18:11
Exactly, I wanted an interpolation between different category markers. That way e.g. blue markers could gradually change to red markers.

**Comment by anitagraser** [comment] 2017-04-02 18:56
Did you close this issue on purpose?

**Comment by 1kastner** [comment] 2017-04-02 20:56
Well, my requested feature is not supported and it is clear what went wrong. Because of that I thought it should be closed but if you want to keep it open for future reference or as a source for to-dos, I will happily re-open it.

**Comment by anitagraser** [comment] 2017-04-29 10:49
This ticket is actually a duplicate of #156

**Closed by anitagraser** 2017-04-29 10:49 UTC
Labels: feature, not-yet-supported
