### ISSUE TITLE
Issues resolving start & end time

### ISSUE THREAD

**Issue by tjukanovt** [anitagraser/TimeManager#260] opened 2018-08-21 17:09 UTC
I have added the following shapefile in QGIS 3.2 and Time Manager 3.0.1 (latest version):
![image](https://user-images.githubusercontent.com/13899537/44416162-ddc3f400-a57a-11e8-8a00-e67a571344ae.png)

When the layer gets added to Time Manager, the start time is resolved to 1970-01-01 00:30:00 and the end time 1970-01-01 05:00:00. The animation clearly works, but the time is incorrect.

I have also had problems adding layers from PostGIS. When adding layers with a lot of rows (+ 5 million), the layer just loads for a while, but nothing gets added to Time Manager. No errors, but nothing just happens. 

I have tried several (file & time) formats and some partly work. Main problems seem to be with PostGIS.

**Comment by anitagraser** [comment] 2018-08-21 18:18
I assume you use the departure column in the above example?

**Comment by tjukanovt** [comment] 2018-08-22 12:11
Yes. Pretty sure I did, but I can double check that one. I can also try and take a Geopackage extract of some the non-working PostGIS layers and share it if it's still not working. I have several examples of datasets that work fine in 2.18 but not in 3.x

**Comment by anitagraser** [comment] 2018-08-22 13:56
Please do.

**Comment by tjukanovt** [comment] 2018-08-22 14:15
So here's a slightly bigger (60 mb) file that works on 2.18 but not in 3.2 (neither the geopackage or from PostGIS). Column field_2 has the time attribute.
https://github.com/tjukanovt/tjukanovt.github.io/blob/master/data2share/trains.gpkg

 I add the layer normally, but and close the time manager window, but then nothing happens and when I open it again, there's nothing there. This is weird, because I am pretty sure that things were working just fine when I did my first tests with 3.x....

**Comment by anitagraser** [comment] 2018-08-25 10:00
Strange! It works for me in QGIS 3.3 without issues. Min and max show that it's data from 2018-06-19 00:00:00 to 23:59:59.

**Comment by tjukanovt** [comment] 2018-09-12 15:38
Installed QGIS 3.3 and reinstalled TimeManager, but still can't get it working. Does QGIS save some cache files if I uninstall the plugin through the GUI? If I remove those manually, could that help?

**Comment by anitagraser** [comment] 2018-09-12 15:47
I don't think that would help. Which operating system are you using? Do you keep the gpkg locally or on a network drive? (Gpkg and Spatialite can be problematic on network drives)

**Comment by tjukanovt** [comment] 2018-09-12 15:51
I am running Windows 10 and using the geopackage locally. But no matter what file format I am using, I can't get TimeManager currently working on 3.x QGIS. Works still fine on 2.18. LTR magic ;)

**Comment by anitagraser** [comment] 2018-10-26 15:31
Closing since I cannot reproduce. If there's new information, this can be reopened.

**Closed by anitagraser** 2018-10-26 15:31 UTC

**Comment by tjukanovt** [comment] 2018-11-02 06:46
Still facing the issue with 3.4. but found a workaround. If I change the time field format in PostGIS to unix time and use that in Time Manager, everything works fine. You can change it with the following SQL
`extract(epoch from yourtimefield::timestamp) as t`
