### ISSUE TITLE
Play button disappears after run the first time QGIS 3.6.2 and Time Manager 3.2.3

### ISSUE THREAD

**Issue by Fragoso09** [anitagraser/TimeManager#312] opened 2019-08-15 15:28 UTC
Hi, seems like the play button dissapears after running and it doesn't come back until I reinstall the pluggin. Any idea of why this is happening?

**Comment by anitagraser** [comment] 2019-08-15 17:33
This is a duplicate of #310

**Closed by anitagraser** 2019-08-15 17:33 UTC
