### ISSUE TITLE
'WMSTRasterLayer' object has no attribute 'resetSubsetString'

### ISSUE THREAD

**Issue by Moon-ika** [anitagraser/TimeManager#257] opened 2018-06-11 15:32 UTC
Hello,

Great plugin! But unfortunately, it keeps erroring on my time aware WMS service (hosted on ArcGIS Server).

I am able to set the Time Manager for my time aware layer first time and I can scroll through time and maps are changing.

But the moment I go back to the Settings, an error message appears:

2018-06-11T16:26:37	WARNING	Traceback (most recent call last):
			  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagercontrol.py", line 271, in showOptionsDialog
			    self.loopAnimation)
			  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagerguicontrol.py", line 394, in showOptionsDialog
			    settings = layer_settings.getSettingsFromLayer(layer)
			  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\layer_settings.py", line 184, in getSettingsFromLayer
			    result.resetSubsetString = layer.resetSubsetString()
			AttributeError: 'WMSTRasterLayer' object has no attribute 'resetSubsetString'

The only way how to make the Time Manager plugin work again is to remove the layer and start again, making it rather time consuming.

Could you please help?

Thanks a lot, Moni

**Comment by anitagraser** [comment] 2018-06-11 16:23
Thank you for reporting this issue. Unfortunately, I currently don't have time to fix this. I'll get to it when I can.

**Comment by merkato** [comment] 2018-06-19 05:07
(...)
`"/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/layer_settings.py",` line 184, in getSettingsFromLayer
    result.resetSubsetString = layer.resetSubsetString()
AttributeError: 'TimeRasterLayer' object has no attribute 'resetSubsetString'`

Same problem with rasters.

**Comment by anitagraser** [comment] 2018-06-19 07:18
Closing as duplicate of #256

**Closed by anitagraser** 2018-06-19 07:18 UTC
