### ISSUE TITLE
casting to char causes table scanning, not index scanning

### ISSUE THREAD

**Issue by chrisgnicholas3** [anitagraser/TimeManager#211] opened 2016-11-30 18:26 UTC
again, first and foremost, THANKS for writing this plugin!

I have a big dataset in PostGIS with a 'date' field, of type 'date':

  id integer NOT NULL,
  msa character varying(5),
  type character varying(25),
  date date,
  value numeric(20,6),
  CONSTRAINT fred_hc_eries_pk PRIMARY KEY (id)

and I build an index on that date field:

CREATE INDEX fred_hc_series_date_idx
  ON fred.hc_series_data
  USING btree (date)

When I run timemanager, I see this SQL in the Postgres logs:
AND (((cast("date" as character) < '1970/06/01' AND cast("date" as character) >= '1970/05/01')))

which causes sequential, full-table scans...    :-(  

When the casting is removed, it will actually use the date index.  :-)

I looked into the query_builder.py code, and clearly that is non-trivial stuff... 

Just wondering if there is a straightforward way to detect and 'just use' native Postgis date fields and associated indexes, and not try to outsmart things to the point it is unusable...

thanks!
Chris

**Comment by anitagraser** [comment] 2016-11-30 19:24
Thanks Chris, I think this is a duplicate of #187

**Comment by chrisgnicholas3** [comment] 2016-12-01 19:09
thanks for pointing this out; that hack works!

WOW!  now I can look at a lot of cool time series!!!

again, THANKS for writing a fantastic plugin!!

Chris

**Comment by chrisgnicholas3** [comment] 2016-12-02 01:48
I also notice that the dialog to set the delay between frames during video frame capture doesn’t seem to work; I want to set it relatively high to let the rendering complete before advancing, so I was setting it to ~10,000 sec, but when I hit “ok” it immediately resets it to ~100 msecs … will file another issue … and look into the sources more closely…

Is there a mechanism to support/fund bug fixing?

thanks again -
Chris

**Closed** 2016-12-02 10:56 UTC

**Comment by anitagraser** [comment] 2016-12-02 10:57
So far we haven't had any offers for funded bug fixes, but let's see if @carolinux would be available for looking into some issues.

**Comment by carolinux** [comment] 2016-12-02 15:23
Hi @chrisgnicholas3 , regarding sponsored bug fixing/development: you can email me at carolinegr@gmail.com and we can arrange something

**Comment by carolinux** [comment] 2017-01-24 12:39
@anitagraser : Please approve the new version of the plugin which handles postgis datetimes in an optimized way. Sponsored by @chrisgnicholas3

**Comment by anitagraser** [comment] 2017-01-24 12:45
Done, thanks!

**Comment by anitagraser** [comment] 2017-02-02 10:27
@carolinux does the latest update work for you? Getting an error here in Plugin Manager

Plugin installation failed:Failed to unzip the plugin package. Probably it's broken or missing from the repository. You may also want to make sure that you have write permission to the plugin directory: ...

**Comment by carolinux** [comment] 2017-02-02 10:30
I don't have time to check. Feel free to re-create the zip and re-upload.
