### ISSUE TITLE
Save time display options to QGIS project file

### ISSUE THREAD

**Issue by nextstopsun** [anitagraser/TimeManager#192] opened 2016-09-06 12:15 UTC
Now time display options aren't saved anywhere, so if you set everything up, then reopen the project they fall back to default, which isn't convenient. They can be saved in the project file and reread when the project is opened.

**Comment by carolinux** [comment] 2016-09-06 12:47
duplicate of #109

**Closed by carolinux** 2016-09-06 12:47 UTC
