### ISSUE TITLE
Error on adding layer: '>=' not supported between instances of 'Exception' and 'int'

### ISSUE THREAD

**Issue by CoryAlbrecht** [anitagraser/TimeManager#317] opened 2019-10-27 15:53 UTC
When trying to add a new layer to Time manager, an error occurs and the layer is not added.

A dialog box pops up saying: An error occurred while trying to add layer timeline_level1 to TimeManager. Cause: '>=' not supported between instances of 'Exception' and 'int'

![image](https://user-images.githubusercontent.com/8172909/67637301-8bcddb00-f8af-11e9-8c7a-a3574bf9e69b.png)

The new layer is a PostGIS layer, as is the one already set up with TimeManager.

Console output from QGIS was:

```
../../src/gui/qgsmapcanvas.cpp:512 : (refresh) [38931ms] CANVAS refresh scheduling
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [2ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [2ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [0ms] CANVAS refresh already scheduled
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] 2019-10-27T11:43:18 TimeManager[0] Time type: DatesAsQDates
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [687ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [38ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [3ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [22ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2019-10-27T11:43:19 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [24ms] 2019-10-27T11:43:19 TimeManager[0] Time format: %Y/%m/%d
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [417ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [33ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [3ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [26ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2019-10-27T11:43:20 PostGIS[1] Error parsing array: ""
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [119ms] 2019-10-27T11:43:20 TimeManager[0] Layer extents(datetime.datetime(1474, 2, 14, 0, 0), datetime.datetime(2099, 12, 31, 0, 0))
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [0ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [2ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [0ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [0ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [3ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [2ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [3ms] CANVAS refresh already scheduled
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [0ms] CANVAS refresh already scheduled
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [8ms] 2019-10-27T11:43:20 TimeManager[0] Time type: DatesAsStrings
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [27ms] 2019-10-27T11:43:20 Python warning[1] warning:/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py:78: DeprecationWarning:

inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()


traceback:  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 517, in saveOptions
    self.signalSaveOptions.emit()
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 669, in saveOptions
    layer = self.createTimeLayerFromRow(row)
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 703, in createTimeLayerFromRow
    self.showMessage(error_msg)
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 256, in showMessage
    QMessageBox.information(self.iface.mainWindow(), msg_type, msg)
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 78, in func
    if inspect.getargspec(self.function).args[-1] == 'context':
  File "/usr/lib/python3.7/inspect.py", line 1078, in getargspec
    DeprecationWarning, stacklevel=2)

../../src/core/qgsmaprendererparalleljob.cpp:64 : (start) [13ms] QThreadPool max thread count is 8
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [6ms] [thread:0x7f621c0067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [373ms] [thread:0x556c9da1ba70] Finished after 15 features
../../src/core/qgsmaprendererparalleljob.cpp:210 : (renderLayersFinished) [1149ms] PARALLEL layers finished
../../src/core/qgsmaprenderercustompainterjob.cpp:338 : (drawLabeling) [176ms] [thread:0x7f621c002290] Draw labeling took (seconds): 0.175
../../src/core/qgsmaprendererparalleljob.cpp:231 : (renderingFinished) [11ms] PARALLEL finished
../../src/gui/qgsmapcanvas.cpp:598 : (rendererJobFinished) [1ms] CANVAS finish! 1
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [371ms] [thread:0x7f621c004860] Finished after 112 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [4ms] [thread:0x7f621c004860] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [38ms] [thread:0x7f621c004860] Finished after 207 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c004860] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [89ms] [thread:0x7f621c004860] Finished after 191 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [4ms] [thread:0x7f621c004860] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [290ms] [thread:0x7f621c0067b0] Finished after 165 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [6ms] [thread:0x7f621c0067b0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c0067b0] Finished after 43 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c0067b0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [33ms] [thread:0x7f621c0067b0] Finished after 65 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c0067b0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [115ms] [thread:0x7f621c0066a0] Finished after 111 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [5ms] [thread:0x7f621c0066a0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c0066a0] Finished after 6 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [7ms] [thread:0x7f621c0066a0] Finished after 16 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [9ms] [thread:0x7f621c0066a0] Finished after 5 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c0066a0] Finished after 6 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [322ms] [thread:0x7f621c006080] Finished after 90 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [6ms] [thread:0x7f621c006080] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [49ms] [thread:0x7f621c006080] Finished after 226 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c006080] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [20ms] [thread:0x7f621c006080] Finished after 60 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c006080] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [44ms] [thread:0x556c9fc32b20] Finished after 21 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [17ms] [thread:0x556c9fc32b20] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [20ms] [thread:0x556c9fc32b20] Finished after 21 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [14ms] [thread:0x556c9fc32b20] Finished after 17 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [4ms] [thread:0x556c9fc32b20] Finished after 3 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [5ms] [thread:0x556c9fc32b20] Finished after 10 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [57ms] [thread:0x7f621c0067e0] Finished after 58 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [10ms] [thread:0x7f621c0067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [35ms] [thread:0x7f621c0067e0] Finished after 123 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f621c0067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c0067e0] Finished after 30 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [2ms] [thread:0x7f621c0067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [99ms] [thread:0x556c9da1ba70] Finished after 188 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [13ms] [thread:0x556c9da1ba70] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [30ms] [thread:0x556c9da1ba70] Finished after 105 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x556c9da1ba70] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [7ms] [thread:0x556c9da1ba70] Finished after 26 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x556c9da1ba70] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [33ms] [thread:0x7f621c002290] Finished after 17 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c002290] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [12ms] [thread:0x7f621c002290] Finished after 7 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [7ms] [thread:0x7f621c002290] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f621c002290] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [4ms] [thread:0x7f621c002290] Finished after 1 features
```

QGIS info from the Help→about dialog:

column |column |column |column |
-- | -- | -- | --
QGIS version | 3.8.3-Zanzibar | QGIS code revision | 0b21735e28
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
This copy of QGIS writes debugging output.
OS Version | Ubuntu 19.04 |   |

**Comment by tasashlar** [comment] 2019-10-30 07:02
Hi Cory, Check for null values in your date field, I get the same errors If I have any nulls.

**Comment by anitagraser** [comment] 2019-11-01 11:52
Closing as duplicate of #305

**Comment by anitagraser** [comment] 2019-11-01 11:53
Similar to #305 this really comes down to #286

**Comment by anitagraser** [comment] 2019-11-01 12:03
@tasashlar Thank you for the pointer! I can reproduce an issue if time values are null. However, the error message there is '>=' not supported between instances of **'TypeError'** and 'int' instead of **'Exception'** and 'int' as @CoryAlbrecht reports

**Comment by anitagraser** [comment] 2019-11-02 11:50
Please try with version 3.4 https://plugins.qgis.org/plugins/timemanager/version/3.4/

**Comment by CoryAlbrecht** [comment] 2019-11-02 18:26
This was a brand new layer - the table existed in PostGIS but there were no rows for features yet, so no date value could have been null.

**Comment by anitagraser** [comment] 2019-11-02 18:36
If this error only occurs for empty PostGIS tables, I'll close this ticket.

**Closed by anitagraser** 2019-11-02 18:36 UTC
Labels: pending feedback
