### ISSUE TITLE
timeframe reset error

### ISSUE THREAD

**Issue by willbreitkreutz** [anitagraser/TimeManager#90] opened 2015-01-26 21:36 UTC
When updating the current time frame, I get  the following error message.  The data re-draws fine, but the error dialogs pop up and I can't clear them if it is in animate mode and eventually crashes QGIS.  It seems to only happen if you manually adjust the slider first, if you just hit play or the left/right arrows after loading the layer(s) it doesn't throw the error.

![1-26-2015 12-10-52 pm](https://cloud.githubusercontent.com/assets/2568631/5908893/03e89a36-a571-11e4-9aa2-44c5e2e90abf.png)

I had it happen in QGIS 2.4 and in 2.6 with time step data in YYYY-MM-DD and in DD/MM/YYYY formats.

**Comment by carolinux** [comment] 2015-01-27 09:33
Which version of Time Manager are you using?

**Comment by willbreitkreutz** [comment] 2015-01-27 16:14
I'm using TimeManager 1.4.1 on Windows 7 Enterprise SP1

Here's the more detailed description of the workflow that I was using:

1. I start from a blank QGIS project, I haven't tried saving it and opening from existing.  
2. Add the shapefile that I want to use
3. Add the layer to TimeManager, setting the start and end fields in 'YYYY-MM-DD' format
![image](https://cloud.githubusercontent.com/assets/2568631/5921859/91af64c6-a60c-11e4-9f2a-3ffa86bed9a2.png)
4. Change the time format setting to %Y-%m-%d
5. If I hit play or the left and right arrows, the render updates and I don't get an error:
![image](https://cloud.githubusercontent.com/assets/2568631/5921900/d57d030c-a60c-11e4-99a3-be66e45bd6c1.png)
6.  If I drag the slider to the right or left, it updates without error, but then if I hid play or the left or right arrows the render refreshes but I get the error.  If I hit play the errors pile up and I can't clear them before they blow out memory or something and crashes QGIS.
![image](https://cloud.githubusercontent.com/assets/2568631/5921924/19d18122-a60d-11e4-9143-a1aabae240b1.png)

Thanks for taking a look!

**Comment by carolinux** [comment] 2015-01-27 16:56
Can you also give me the file or a sample thereof? A bit short on shapefiles with QDates on them. My gmail handle is carolinegr

**Comment by carolinux** [comment] 2015-01-27 17:07
So, you don't need to send me a file at the moment, but it would be nice. The issue is indeed in reading and writing settings (which is done under the hood even if the user doesn't save the project). It will be fixed in the next release. As a quick fix so that you don't get crashes and you can create your animations, find the file: timemanagerprojecthandler.py and where it says
```
QMessageBox.information(self.iface.mainWindow(),'Debug Output','Wrong type for
             '+attribute+'!\nType: '+str(type(value)))
```
just comment it out and replace it with
```
pass
```
Then saving may not work great, but you will get rid of the popup. 

Here http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins.html at the top you can see possible locations of where the timemanager directory with this file can be.

**Comment by willbreitkreutz** [comment] 2015-01-27 19:07
Thanks so much, that work-around is going to work great.  I'll send you a sub-set of the data that I am using, the full shapefile is almost 80MB.

Thanks again!

**Comment by carolinux** [comment] 2015-01-31 16:13
After settings overhaul, this works.

**Closed by carolinux** 2015-01-31 16:13 UTC
Labels: bug
